name: Cron Job

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make a change
        run: |
          echo "Last run: $(date -u)" > cron.txt

      - uses: stefanzweifel/git-auto-commit-action@v5
